config/routes.rb
Rails.application.routes.draw do
  get   'quiz/question/:id'     => "quiz#question",     as: :quiz_question
  post  'quiz/check_answer/:id' => 'quiz#check_answer', as: :quiz_check_answer

  resources :questions
  resources :results, only: :index
  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'

end

app/models/ckeditor/asset.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string           not null
#  data_content_type :string
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string           not null
#  data_content_type :string
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string           not null
#  data_content_type :string
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  content    :text
#  answer     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  validates :content, :answer, presence: true

  def next
    Question.where("id > ?", id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_first_question

  def get_first_question
    @first_question = Question.first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:score] = 0
    session[:question_number] = 1
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :answer)
    end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  before_action :check_score, only: :question
  before_action :set_question
  before_action :increase_question_number, only: :check_answer

  def question
  end

  def check_answer
    answer_score = ScoringAction.get_answer_score(@question.answer, question_params[:answer])
    answer_status = ScoringAction.get_answer_status(answer_score)
    session[:score] += 1 if answer_status.eql? true

    if @question.next
      if answer_status.eql? true
        redirect_to quiz_question_path(@question.next), notice: "Correct Answer!"
      else
        redirect_to quiz_question_path(@question.next), alert: "Wrong Answer!"
      end
    else
      redirect_to results_path, notice: "Finished!"
    end
  end

  private
    def check_score
      redirect_to root_path if session[:score].nil?
    end

    def set_question
      @question = Question.where(id: params[:id]).first
    end

    def question_params
      params.require(:question).permit(:answer)
    end

    def increase_question_number
      session[:question_number] += 1
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :check_score
  after_action :clear_session

  def index
    @result_score = session[:score]
  end

  private
    def check_score
      redirect_to root_url if session[:score].nil?
    end

    def clear_session
      session[:score] = nil if session[:score].present?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/home/index.html.slim
.row
  .col-md-6.col-md-offset-3.text-center.col-xs-12.box-show-homepage
    h1 Welcome to Quiz Master
    - if @first_question
      p Click button below to start the Quiz!
      = link_to "Take a Quiz!", quiz_question_path(@first_question), class: "btn btn-success"
      hr
      p OR
    - else
      p No question available yet
      hr
    = link_to "Add new Questions", new_question_path, class: "btn btn-primary"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Quiz Master"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to "Quiz Master", root_path, class: "navbar-brand"
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav.navbar-right
            - if @first_question
              li= link_to "Take a Quiz!", quiz_question_path(@first_question)
            li= link_to "Manage Questions", questions_path

    .container
      .row
        .col-md-12
          = bootstrap_flash
          = yield

app/views/questions/_form.html.slim
= simple_form_for(@question) do |f|
  = f.error_notification

  .container
    .row.row-form
      .col-md-1.col-md-offset-1.col-xs-12
        = f.label :content
      .col-md-8.col-xs-12
        .form-inputs
          = f.cktext_area :content
    .row.row-form
      .col-md-1.col-md-offset-1.col-xs-12
        = f.label :answer
      .col-md-8.col-xs-12
        .form-inputs
          = f.input :answer, label: false, input_html: {autocomplete: "off"}

  .form-actions.text-center
    = f.button :submit, class: "btn btn-success"
    | &nbsp;
    = link_to 'Back to Questions', questions_path, class: "btn btn-warning"

app/views/questions/edit.html.slim
h3.text-center Editing question
br

== render 'form'

app/views/questions/index.html.slim
h3.text-center Listing questions
br

table.table.table-bordered.table-striped
  thead
    tr
      th.text-center No
      th Content
      th Answer
      th width="220"

  tbody
    - @questions.each_with_index do |question, index|
      tr
        td.text-center = index + 1
        td = raw question.content.html_safe
        td = question.answer
        td
          = link_to 'Show', question, class: "btn btn-info"
          | &nbsp;
          = link_to 'Edit', edit_question_path(question), class: "btn btn-success"
          | &nbsp;
          = link_to 'Destroy', question, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger"

br

= link_to 'New Question', new_question_path, class: "btn btn-primary text-center"

app/views/questions/new.html.slim
h3.text-center New question
br

== render 'form'

app/views/questions/show.html.slim
.container
  .row.row-form
    .col-md-8.col-md-offset-2.col-xs-12.box-show-question
      p
        strong Content:
        = @question.content.html_safe
      p
        strong Answer:
        p = @question.answer

      .text-center
        = link_to 'Edit Question', edit_question_path(@question), class: "btn btn-primary"
        | &nbsp;
        = link_to 'Back to Questions', questions_path, class: "btn btn-warning"

app/views/quiz/question.html.slim
.container
  .row.row-form
    .col-md-8.col-md-offset-2.col-xs-12
      - if @question
        h4 = @question.content.html_safe
        = simple_form_for :question, url: quiz_check_answer_path(@question) do |f|
          = f.input :answer, required: true, label: false, input_html: {value: nil, autocomplete: "off", placeholder: "Your answer here..."}, validate: { presence: true }
          = f.button :submit, "Submit", class: "btn btn-primary"
      - else
        h4 Question is not available
      p.text-right = "Question number #{session[:question_number]} from total #{pluralize(Question.count, 'question')}"

app/views/results/index.html.slim
.container
  .row.row-form
    .col-md-8.col-md-offset-2.col-xs-12.text-center
      h1 = "Your score is #{@result_score}"
      h4 = "From total #{pluralize(Question.count, 'question')}"
      hr
      = link_to "Back to Homepage", root_path, class: "btn btn-primary"